[tool.poetry]
name = "bend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
biopython = ">=1.81"
pandas = ">=2.0.2"
scikit-learn = ">=1.2.2"
torch = ">=2.0.1"
tqdm = ">=4.65.0"
transformers = ">=4.30.1,<=4.33.3"
hydra-core = ">=1.3.1"
wandb = ">= 0.19.7"
einops = "^0.8.1"
torchvision = "^0.22.0"
hydra-joblib-launcher = "^1.2.0"
webdataset = "^0.2.111"
beautifulsoup4 = "^4.13.4"
lxml = "^5.4.0"
h5py = "^3.13.0"
pysam = "^0.23.0"
peft = "0.8.2"
matplotlib = "^3.10.3"
beanie = "^2.0.0"
python-dotenv = "^1.1.1"
motor = "^3.7.1"
pytorch-lightning = "^2.5.3"
matplotlib-venn = "^1.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
